package ProjetoIntegrador;

public class TestesComStrings {

    public static void main(String[] args) {
        //Tamanho total de cada linha: 1200 caracteres
        String headerGeralDoArquivo = "000000000004 BANCO FAKERALL S.A 20220223                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ";
        String headerLote = "10010000010001GOLD MASTERCARD     01010605000201010005                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ";
        String detalhe = "20010000010000010000718294                              1426                                    02/22                                   CLARA RIBEIRO                           746                                     B2231236880519753^RIBEIRO/CLARA             ^2702206000000000000995000000     2231236880519753=27022060000099500000                                                                                                             *1CLARA RIBEIRO             RUA BELA VISTA                                    CENTRO              NOVO HAMBURGO       RS93320340                                                                                                                                                                                                                                                                       001                           0000002000000530000000100                B2231236880519753^RIBEIRO/CLARA             ^2702206000000000000287000000     2231236880519753=27022060000028700000              000000000011                                                                                                                 757                                         ";
        String traillerLote = "30010000010000001                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ";
        String traillerGeral = "90000001                                                                                                                                                                          ";

        System.out.println(headerGeralDoArquivo.length());
    }

}
